ci:
  autofix_commit_msg: "chore(pre-commit): auto fix by pre-commit hooks"
  autofix_prs: true
  autoupdate_branch: master
  autoupdate_schedule: weekly
  autoupdate_commit_msg: "chore(pre-commit): auto update by pre-commit hooks"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
