name: Build & Release RinUI Gallery

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v5

      - name: 📦 Set up Python & Install uv
        uses: astral-sh/setup-uv@v6

      - name: 📦 Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ github.workflow }}-

      - name: 📦 Install dependencies
        run: |
          uv sync
          uv pip install pyinstaller

      - name: 🔨 Build Gallery (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          uv run pyinstaller --noconsole \
            --icon "examples/assets/gallery.ico" \
            --add-data "RinUI:RinUI" \
            --add-data "examples/assets:assets" \
            --add-data "examples/components:components" \
            --add-data "examples/languages:languages" \
            --add-data "examples/pages:pages" \
            --add-data "examples/gallery.qml:." \
            --paths=. \
            --contents-directory . \
            --name=RinUIGallery \
            examples/gallery.py

      - name: 🔨 Build Gallery (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          uv run pyinstaller --noconsole \
            --icon "examples/assets/gallery.icns" \
            --add-data "RinUI:RinUI" \
            --add-data "examples/assets:assets" \
            --add-data "examples/components:components" \
            --add-data "examples/languages:languages" \
            --add-data "examples/pages:pages" \
            --add-data "examples/gallery.qml:." \
            --paths=. \
            --contents-directory . \
            --name=RinUIGallery \
            examples/gallery.py

      - name: 📦 Zip build (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Compress-Archive -Path dist/RinUIGallery/* -DestinationPath dist/RinUIGallery-Windows.zip

      - name: 📦 Zip build (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent RinUIGallery.app RinUIGallery-macOS.zip

      - name: ☁️ Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: RinUIGallery-Windows
          path: dist/RinUIGallery-Windows.zip

      - name: ☁️ Upload artifact (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: RinUIGallery-macOS
          path: dist/RinUIGallery-macOS.zip

  release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ⬇️ Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist/

      - name: 🗃 Move release files to root dist/
        run: |
          echo "::group::Show downloaded structure"
          ls -R dist/
          echo "::endgroup::"
          mv dist/RinUIGallery-Windows/*.zip dist/
          mv dist/RinUIGallery-macOS/*.zip dist/

      - name: 🧱 Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - name: 📜 Generate CHANGELOG.md
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git cliff --latest --tag "${{ github.ref_name }}" --config .git-cliff.toml --github-repo "${{ github.repository }}" > CHANGELOG.md

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: RinUI Gallery ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
          files: |
            dist/RinUIGallery-Windows.zip
            dist/RinUIGallery-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
